### ISSUE TITLE
Server crash when closing

### ISSUE THREAD

**Issue by TheVeryStarlk** [ObsidianMC/Obsidian#418]
Before posting your issue; please check the following box:

- [X] I am aware that I am making a GitHub issue for the Obsidian that is a minecraft server, and not the Obsidian that is a Markdown editor.

--------------------

```
[01:16:28] [Crit]  [ObsidianHostingService] Obsidian has crashed!
[01:16:28] [Crit]  [ObsidianHostingService] Try turning it off and on again...
[01:16:28] [Crit]  [ObsidianHostingService] Reason: Object reference not set to an instance of an object.
[01:16:28] [Crit]  [ObsidianHostingService]    at Obsidian.Server.AcceptClientsAsync() in C:\Users\starl\RiderProjects\Obsidian\Obsidian\Server.cs:line 369
[01:16:28] [Crit]  [ObsidianHostingService]    at Obsidian.Server.RunAsync() in C:\Users\starl\RiderProjects\Obsidian\Obsidian\Server.cs:line 295
[01:16:28] [Crit]  [ObsidianHostingService]    at Obsidian.Server.RunAsync() in C:\Users\starl\RiderProjects\Obsidian\Obsidian\Server.cs:line 307
[01:16:28] [Crit]  [ObsidianHostingService]    at Obsidian.Hosting.ObsidianHostingService.ExecuteAsync(CancellationToken cToken) in C:\Users\starl\RiderProjects\Obsidian\Obsidian\Hosting\ObsidianHostingService.cs:line 29
```

How to re-produce:
1. Start the server
2. Go to Minecraft client and keep refreshing the server list till the server's console says: `Listening for new clients`
3. Close the server

**Comment by TheVeryStarlk** [comment]
I'm trying to fix it
